<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dei</string>
	</array>
	<key>name</key>
	<string>Doomsday Info</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#quoted_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x) (script) \s* ( ([".\w]+) \s+ ([".\w]+) \s* )* ({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.doomsdayinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.other.attribute-value.doomsdayinfo</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doomsdayinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.script.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.doomsday</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#definitions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(True|False)\b</string>
			<key>name</key>
			<string>constant.language.doomsdayinfo</string>
		</dict>
		<key>def_condition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(condition)\s*(:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline.condition</string>
		</dict>
		<key>def_list</key>
		<dict>
			<key>begin</key>
			<string>([".\w]+)\s*(&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bracket.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bracket.doomsdayinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.value.list.doomsdayinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted_string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.definition.separator</string>
				</dict>
			</array>
		</dict>
		<key>def_scripted</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([".\w]+)\s*(\$:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline.scripted.doomsdayinfo</string>
		</dict>
		<key>def_scripted_expr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doomsdayinfo</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([".\w]+)\s*(\$=)(.*)(})?</string>
			<key>name</key>
			<string>meta.definition.singleline.scriptedexpr.doomsdayinfo</string>
		</dict>
		<key>def_single</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.raw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([".\w]+)\s*(:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline</string>
		</dict>
		<key>def_value</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted_string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([".\w]+)\s*(=)\s*(.*)</string>
			<key>name</key>
			<string>meta.definition.singlevalue</string>
		</dict>
		<key>definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#def_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_condition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_scripted_expr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_scripted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_value</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x) ([".\w]+) \s* ({|\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#implicit_group</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.doomsdayinfo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)|}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.doomsdayinfo</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.group</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x) ([".\w]+ \s+)? ([".\w]+) (\s+ ([".\w]+) \s+ ([".\w]+) )* \s* ({|\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#group_type</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#identifier</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.doomsdayinfo</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.attribute-value.doomsdayinfo</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.doomsdayinfo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)|}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.doomsdayinfo</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.group</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x) ([".\w]+) \s+ ([@".\w]+) \s* ({|\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.doomsdayinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#identifier</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.doomsdayinfo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)|}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.doomsdayinfo</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.group</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>group_type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bgroup\b</string>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>entity.name.type.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quoted_string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[@\w.]+</string>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
		<key>implicit_group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bgroup\b</string>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(group|script|inherits|condition)\b</string>
			<key>name</key>
			<string>keyword.control.doomsdayinfo</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.doomsdayinfo</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!@)[-+]?\.?[_0-9]+</string>
			<key>name</key>
			<string>constant.numeric.doomsdayinfo</string>
		</dict>
		<key>quoted_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.doomsdayinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.doomsdayinfo</string>
	<key>uuid</key>
	<string>CF5BEEB9-0B49-4DE2-AB4F-46F5EC6182CE</string>
</dict>
</plist>
